### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: ''

### ISSUE THREAD

**Issue by masx200** [obaby/mht-image-extractor#6]
版本号是0.9.22

```
$ python /storage/emulated/0/mht-image-extractor/baby_mht_image_extractor.py -p /sdcard/我的文档/文件夹/
****************************************************************************************************
[S] 开始任务......
[C] 输入文件:
[C] 输入目录:/sdcard/我的文档/文件夹/
[C] 输出目录:/storage/emulated/0/mht-image-extractor/out
Traceback (most recent call last):
  File "/storage/emulated/0/mht-image-extractor/baby_mht_image_extractor.py", line 295, in <module>
    main(sys.argv[1:])
  File "/storage/emulated/0/mht-image-extractor/baby_mht_image_extractor.py", line 257, in main
    btype = get_browser_type(input_file)
  File "/storage/emulated/0/mht-image-extractor/baby_mht_image_extractor.py", line 216, in get_browser_type
    with open(input_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: ''
$ 
```

**Comment by masx200** [comment]
指定了输入文件夹的情况下报错

**Comment by masx200** [comment]
@obaby

**Comment by masx200** [comment]
```
if input_file !=''b:
    btype = get_browser_type(input_file)
    print("[B] 浏览器：", btype)
```

**Comment by obaby** [comment]
> 修改257行
> 
> ```python
> btype=""
> if input_file !='':
>     btype = get_browser_type(input_file)
>     print("[B] 浏览器：", btype)
> ```

fixed
